# Source: cluster-api-aws/templates/aws-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: 08510d6e-3f39-44ec-9f28-75d3f5aacfae-control-plane
  namespace: 08510d6e-3f39-44ec-9f28-75d3f5aacfae
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: tks-seoul
      rootVolume:
        size: 20
        type: gp2
