# Source: cluster-api-aws/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: 08510d6e-3f39-44ec-9f28-75d3f5aacfae
  namespace: 08510d6e-3f39-44ec-9f28-75d3f5aacfae
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: 08510d6e-3f39-44ec-9f28-75d3f5aacfae
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "08510d6e-3f39-44ec-9f28-75d3f5aacfae-control-plane"
