# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 08510d6e-3f39-44ec-9f28-75d3f5aacfae-capi-aws-check
  namespace: 08510d6e-3f39-44ec-9f28-75d3f5aacfae
spec:
  template:
    metadata:
      name: 08510d6e-3f39-44ec-9f28-75d3f5aacfae-capi-aws
    spec:
      serviceAccountName: 08510d6e-3f39-44ec-9f28-75d3f5aacfae-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 08510d6e-3f39-44ec-9f28-75d3f5aacfae
        - 08510d6e-3f39-44ec-9f28-75d3f5aacfae
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 08510d6e-3f39-44ec-9f28-75d3f5aacfae-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
